package utils

const (
	EMPTY_STRING                  = ""
	POST                          = "POST"
	GET                           = "GET"
	HEADER_CONTENT_TYPE           = "Content-Type"
	CONTENT_TYPE_APPLICATION_JSON = "application/json"
	OPEN_API_GOOGLE               = "google"
	HEADER_AUTHORIZATION          = "Authorization"

	CONFIG_APP_URL     = "APP_URL"
	CONFIG_APP_ENV     = "APP_ENV"
	CONFIG_APP_DEBUG   = "APP_DEBUG"
	CONFIG_APP_VERSION = "APP_VERSION"
	CONFIG_APP_NAME    = "SERVICE_NAME"
	CONFIG_APP_PORT    = "APP_PORT"
	CONFIG_GIN_MODE    = "GIN_MODE"

	CONFIG_DB_HOST                    = "DB_HOST"
	CONFIG_DB_PORT                    = "DB_PORT"
	CONFIG_DB_NAME                    = "DB_NAME"
	CONFIG_DB_USERNAME                = "DB_USERNAME"
	CONFIG_DB_PASSWORD                = "DB_PASSWORD"
	CONFIG_DB_SCHEMA                  = "DB_SCHEMA"
	CONFIG_DB_DRIVER                  = "DB_DRIVER"
	CONFIG_DB_MAX_CONNECTION          = "DB_MAX_CONNECTION"
	CONFIG_DB_MAX_IDLE_CONNECTION     = "DB_MAX_IDLE_CONNECTION"
	CONFIG_DB_MAX_LIFETIME_CONNECTION = "DB_MAX_LIFETIME_CONNECTION"

	CONFIG_JWT_SECRET_ACCESS_TOKEN  = "JWT_SECRET_ACCESS_TOKEN"
	CONFIG_AUTH_EXPIRE_ACCESS_TOKEN = "AUTH_EXPIRE_ACCESS_TOKEN"
)
